### ISSUE TITLE
[Ext/Decoders/BoundingBox] Bug: enum variables are always larger than -1

### ISSUE THREAD

**Issue by wooksong** [wooksong/contributon2019-nns#16]
```c
 382     if (NULL == param || *param == '\0' || bdata->mode < 0) {                   
 383       GST_ERROR ("Please set the valid mode at option1");                       
 384       return FALSE;                                                             
 385     }                           
```

bdata->mode is a variable of enum type so that it is always a positive value or zero. 
Some compilers (i.e., clang) would complain about it. Need to fix this logical bug.

**Comment by niklasjang** [comment]
https://github.com/nnsuite/nnstreamer/pull/1758/commits/693048f24de084b0bb810e51192a2e5476b14586

PR 결과 기다렸다가 리포트 하겠습니다

**Comment by wooksong** [comment]
Merged!
