### ISSUE TITLE
[Android/Api] is "zip"  need?

### ISSUE THREAD

**Issue by Lee-WonJun** [wooksong/contributon2019-nns#22]
api/android/build-android-lib.sh

해당 파일에서 

zip이 패키지에 포함되어 있는지 검사를 진행합니다.

그러나 zip 패키지의 경우
run_unittest 옵션이 'yes' 인 경우에만 사용하는 패키지입니다.

run_unittest 의 기본 옵션이 'no'인데 no일때는 검사할 필요가 없지 않을까요?

**Comment by wooksong** [comment]
그렇다면 필요하단 이야기 아닌가요? 차라리 현재 오에스 정보를 얻어서 apt yum pacman zypper 등으로 필요한 패키지를 자동으로 받아오게 하는 것은 어때요?

**Comment by Lee-WonJun** [comment]
아 제가 말하고자 한것은
run_unittest 이 yes일때는 zip패키지 검사를 진행하고 
아닐때는 굳이 zip 패키지 검사가 필요없을것같다고 말씀드린것입니다.

os정보를 얻어서 자동으로 패키지를 받아오는것도 좋을것 같습니다

**Comment by wooksong** [comment]
오히려 가독성을 해칠 것 같은데 잘 모르겠네요.
